"""Tuple composition: the 21^X generative principle.

Tier WAMAH-S[X] contains exactly 21^X items per category, one per ordered
length-X tuple over the 21-probe alphabet. S1 tuples are the single probes,
hand-authored in data/seed/S1. S2 and above are generated by renderers.
"""

from __future__ import annotations

import itertools
from pathlib import Path

from wamah.alphabet import PROBE_LIST, probe_ids
from wamah.schema import Category

TIERS = {"S1": 1, "S2": 2, "S3": 3, "S4": 4, "S5": 5}

# Tiers S4 (21^4) and S5 (21^5) are defined by the spec but not materialized
# yet - generating them is deferred until disk/time budget allows. The
# generator refuses them with a clear message instead of filling the drive.
MAX_GENERATED_TIER = 3

CATEGORIES = [Category.Q, Category.SC, Category.P, Category.D]

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
SEED_DIR = DATA_DIR / "seed"
GENERATED_DIR = DATA_DIR / "generated"


def parse_tier(tier: str) -> int:
    tier = tier.upper()
    if tier.startswith("S"):
        tier = tier[1:]
    x = int(tier)
    if x < 1:
        raise ValueError("tier exponent must be >= 1")
    return x


def tier_name(x: int) -> str:
    return f"S{x}"


def items_per_category(x: int) -> int:
    return 21 ** x


def total_items(x: int) -> int:
    return 4 * (21 ** x)


def enumerate_tuples(x: int) -> list[tuple[str, ...]]:
    """All ordered length-X tuples over the probe alphabet (lexicographic)."""
    ids = probe_ids()
    return list(itertools.product(ids, repeat=x))


def item_id(tier: str, category: Category, probes: tuple[str, ...] | list[str], harness_id: str) -> str:
    tag = "_".join(probes)
    return f"{tier}-{category.value}-{tag}-{harness_id}"


def harness_id_for(tier: str, category: Category, probes: tuple[str, ...] | list[str]) -> str:
    """Stable round-robin harness assignment from a tuple's global index."""
    from wamah.alphabet import harness_for_index
    x = len(probes)
    ids = probe_ids()
    index = 0
    for pid in probes:
        index = index * 21 + ids.index(pid)
    # offset per category so the same tuple does not always meet the same trap
    cat_offset = {"Q": 0, "Sc": 5, "P": 10, "D": 15}[category.value]
    return harness_for_index(index + cat_offset).id


def verify_tier_counts(x: int) -> dict[str, int]:
    """Assert the defining invariant: 21^X items in every category."""
    expected = items_per_category(x)
    actual = {c.value: len(enumerate_tuples(x)) for c in CATEGORIES}
    for cat, n in actual.items():
        if n != expected:
            raise AssertionError(f"tier S{x} category {cat}: expected {expected}, got {n}")
    return {"expected": expected, **actual}


def tier_dir(tier: str, root: Path | None = None) -> Path:
    """Where items of a tier live: seeds for S1, generated for S2+."""
    x = parse_tier(tier)
    base = (root or DATA_DIR)
    if x == 1:
        return SEED_DIR / "S1"
    return base / "generated" / tier.upper()


if __name__ == "__main__":
    for x in (1, 2, 3):
        print(f"S{x}: {items_per_category(x)}/category, {total_items(x)} total, "
              f"HARM reach={__import__('wamah.alphabet', fromlist=['human_harm_share']).human_harm_share(x):.3f}")
        verify_tier_counts(x)
    print("counts OK")
